# Generated by Django 5.0.4 on 2024-04-18 20:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medico", "0002_dadosmedico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DadosMedico",
            new_name="DadosMedicos",
        ),
    ]
